---
title: "List of datasets, functions, classes and methods"
author: "Gauthier Magnin"
date: "Last update: `r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{List of datasets, functions, classes and methods}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{css, echo=FALSE}
h1:not(.title) {
  margin-top: 1.4rem;
}
```



The package help page: [uom.dat](../html/uom.dat-package.html)



# Datasets

Datasets used as examples:

* [oedb_sample](../html/oedb_sample.html)
* [substances_information](../html/substances_information.html)
* [TS_instance](../html/TS_instance.html)
* [TA_instance](../html/TA_instance.html)



# About transaction set

The class: [TransactionSet](../html/TransactionSet-class.html)

Making *TransactionSet* objects:

* [transaction.set](../html/transaction.set.html)
* [make_transactions](../html/make_transactions.html)
* [make_OE_transactions](../html/make_OE_transactions.html)
* [\[](../html/sub-TransactionSet-ANY-ANY-ANY-method.html) and [\[<-](../html/sub-TransactionSet-ANY-ANY-ANY-method.html)
* [subset](../html/subset-TransactionSet-method.html)
* [reorder](../html/reorder-TransactionSet-method.html)

Search in transactions:

* [get_all_items](../html/get_all_items-TransactionSet-method.html)
* [get_itemsets](../html/get_itemsets-TransactionSet-method.html)
* [get_items_from_info](../html/get_items_from_info-TransactionSet-method.html)
* [get_info_from_items](../html/get_info_from_items-TransactionSet-method.html)

Search for transactions:

* [get_complex_trx](../html/get_complex_trx-TransactionSet-method.html)
* [get_simple_trx](../html/get_simple_trx-TransactionSet-method.html)
* [get_trx_from_items](../html/get_trx_from_items-TransactionSet-method.html)
* [get_trx_from_info](../html/get_trx_from_info-TransactionSet-method.html)

Computations on transactions:

* [complexity_ratio](../html/complexity_ratio-TransactionSet-method.html)
* [complexity_index](../html/complexity_index-TransactionSet-method.html)
* [co_occurrence_matrix](../html/co_occurrence_matrix-TransactionSet-method.html)

Making charts about transactions:

* [itemset_chart](../html/itemset_chart-TransactionSet-method.html)
* [co_occurrence_chart](../html/co_occurrence_chart-TransactionSet-method.html)



# About transaction analysis

The class: [TransactionAnalyzer](../html/TransactionAnalyzer-class.html)

Making *TransactionAnalyzer* objects:

* [transaction.analyzer](../html/transaction.analyzer.html)
* [init](../html/init-TransactionAnalyzer-method.html) and [is_init](../html/is_init-TransactionAnalyzer-method.html)
* [reset](../html/reset-TransactionAnalyzer-method.html)
* [\[](../html/sub-TransactionAnalyzer-ANY-ANY-ANY-method.html) and [\[<-](../html/sub-TransactionAnalyzer-ANY-ANY-ANY-method.html)

Making charts:

* [spectrosome_chart](../html/spectrosome_chart-TransactionAnalyzer-method.html)
* [cluster_chart](../html/cluster_chart-TransactionAnalyzer-method.html)
* [spectrum_chart](../html/spectrum_chart-TransactionAnalyzer-method.html)
* [itemset_chart](../html/itemset_chart-TransactionAnalyzer-method.html)
* [category_tree_chart](../html/category_tree_chart-TransactionAnalyzer-method.html)
* [co_occurrence_chart](../html/co_occurrence_chart-TransactionAnalyzer-method.html)

Search for nodes or patterns:

* [get_nodes](../html/get_nodes-TransactionAnalyzer-method.html)
* [get_patterns](../html/get_patterns-TransactionAnalyzer-method.html)
* [get_complexes](../html/get_complexes-TransactionAnalyzer-method.html)
* [get_isolates](../html/get_isolates-TransactionAnalyzer-method.html)
* [get_non_isolates](../html/get_non_isolates-TransactionAnalyzer-method.html)

Search for links between nodes or between patterns:

* [get_links](../html/get_links-TransactionAnalyzer-method.html)

Computations on spectrosomes:

* [degree](../html/degree-TransactionAnalyzer-method.html)
* [network_density](../html/network_density-TransactionAnalyzer-method.html)

Computations on nodes and patterns:

* [frequency_by_complexity](../html/frequency_by_complexity-TransactionAnalyzer-method.html)
* [define_dynamic_status](../html/define_dynamic_status-TransactionAnalyzer-method.html)

Saving nodes or patterns:

* [export](../html/export-TransactionAnalyzer-method.html)



# About association rules and sets

Extracting, visualizing and saving association rules:

* [extract_rules](../html/extract_rules-TransactionAnalyzer-method.html)
* [rules_chart](../html/rules_chart-TransactionAnalyzer-method.html)
* [export](../html/export-TransactionAnalyzer-method.html)

Switching between mathematical notation and vector notation for sets:

* [vector_notation](../html/vector_notation.html)
* [set_notation](../html/set_notation.html)



# About the maximum cumulative ratio approach

Computation of the main indicators:

* [hazard_quotient](../html/hazard_quotient.html)
* [hazard_index](../html/hazard_index.html)
* [maximum_hazard_quotient](../html/maximum_hazard_quotient.html)
* [maximum_cumulative_ratio](../html/maximum_cumulative_ratio.html)
* [missed_toxicity](../html/missed_toxicity.html)

Computation of additional indicators:

* [reciprocal_of_mcr](../html/reciprocal_of_mcr.html)
* [top_hazard_quotient](../html/top_hazard_quotient.html)
* [classify_mixture](../html/classify_mixture.html)

Summarising indicators:

* [mcr_summary](../html/mcr_summary.html)
* [mcr_chart](../html/mcr_chart.html)
* [thq_pairs](../html/thq_pairs.html)
* [thq_by_group](../html/thq_by_group.html)

Application of the approach according to a classification

* [mcr_approach_by_class](../html/mcr_approach_by_class.html)
* [mcr_summary_by_class](../html/mcr_summary_by_class.html)
* [mcr_chart_by_class](../html/mcr_chart_by_class.html)
* [thq_pairs_by_class](../html/thq_pairs_by_class.html)
* [thq_by_group_by_class](../html/thq_by_group_by_class.html)



# About lists

Computations on lists:

* [intersect_on_list](../html/intersect_on_list.html)
* [union_on_list](../html/union_on_list.html)
* [table_on_list](../html/table_on_list.html)

Transformation of lists and transformation into lists:

* [invert_list](../html/invert_list.html)
* [coerce_list](../html/coerce_list.html)
* [coerce_to_list](../html/coerce_to_list.html)

Search in lists:

* [nth_values](../html/nth_values.html)



---
