---
title: "List of datasets, functions, classes and methods"
author: "Gauthier Magnin"
date: "Last update: `r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{List of datasets, functions, classes and methods}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{css, echo=FALSE}
h1:not(.title) {
  margin-top: 1.4rem;
}
```



The package help page: [oedb.analysis.tools](../html/oedb.analysis.tools-package.html)



# Datasets

Datasets used as examples:

* [oedb_sample](../html/oedb_sample.html)
* [substances_information](../html/substances_information.html)
* [SA_instance](../html/SA_instance.html)



# About observations

Making observations:

* [make_observations](../html/make_observations.html)
* [make_INRS_observations](../html/make_INRS_observations.html)

Search for observations:

* [get_complex_obs](../html/get_complex_obs.html)
* [get_simple_obs](../html/get_simple_obs.html)
* [get_obs_from_items](../html/get_obs_from_items.html)
* [get_obs_from_info](../html/get_obs_from_info.html)

Search in observations:

* [get_all_items](../html/get_all_items.html)
* [get_items_from_info](../html/get_items_from_info.html)
* [get_info_from_items](../html/get_info_from_items.html)

Computations on observations:

* [complexity_ratio](../html/complexity_ratio.html)
* [complexity_index](../html/complexity_index.html)
* [co_occurrence_matrix](../html/co_occurrence_matrix.html)

Making charts about observations:

* [co_occurrence_chart](../html/co_occurrence_chart-SpectralAnalyzer-method.html)



# About spectral analysis

The class: [SpectralAnalyzer](../html/SpectralAnalyzer-class.html)

Making *SpectralAnalyzer* objects:

* [spectral.analyzer](../html/spectral.analyzer.html)
* [reset](../html/reset-SpectralAnalyzer-method.html)
* [\[](../html/sub-SpectralAnalyzer-ANY-ANY-ANY-method.html) and [\[<-](../html/sub-SpectralAnalyzer-ANY-ANY-ANY-method.html)

Making charts:

* [spectrosome_chart](../html/spectrosome_chart-SpectralAnalyzer-method.html)
* [cluster_chart](../html/cluster_chart-SpectralAnalyzer-method.html)
* [spectrum_chart](../html/spectrum_chart-SpectralAnalyzer-method.html)
* [pattern_chart](../html/pattern_chart-SpectralAnalyzer-method.html)
* [category_tree_chart](../html/category_tree_chart-SpectralAnalyzer-method.html)
* [co_occurrence_chart](../html/co_occurrence_chart-SpectralAnalyzer-method.html)

Search for nodes or patterns:

* [get_nodes](../html/get_nodes-SpectralAnalyzer-method.html)
* [get_patterns](../html/get_patterns-SpectralAnalyzer-method.html)
* [get_complexes](../html/get_complexes-SpectralAnalyzer-method.html)
* [get_isolates](../html/get_isolates-SpectralAnalyzer-method.html)
* [get_non_isolates](../html/get_non_isolates-SpectralAnalyzer-method.html)

Search for links between nodes or between patterns:

* [get_links](../html/get_links-SpectralAnalyzer-method.html)

Computations on spectrosomes:

* [degree](../html/degree-SpectralAnalyzer-method.html)
* [network_density](../html/network_density-SpectralAnalyzer-method.html)

Saving nodes or patterns:

* [save_characteristics](../html/save_characteristics-SpectralAnalyzer-method.html)



# About association rules and sets

Extracting, visualizing and saving rules:

* [extract_rules](../html/extract_rules-SpectralAnalyzer-method.html)
* [rules_chart](../html/rules_chart-SpectralAnalyzer-method.html)
* [save_characteristics](../html/save_characteristics-SpectralAnalyzer-method.html)

Switching between mathematical notation and vector notation for sets:

* [vector_notation](../html/vector_notation.html)
* [set_notation](../html/set_notation.html)



# About the maximum cumulative ratio approach

Computation of the main indicators:

* [hazard_quotient](../html/hazard_quotient.html)
* [hazard_index](../html/hazard_index.html)
* [maximum_hazard_quotient](../html/maximum_hazard_quotient.html)
* [maximum_cumulative_ratio](../html/maximum_cumulative_ratio.html)
* [missed_toxicity](../html/missed_toxicity.html)

Computation of additional indicators:

* [reciprocal_of_mcr](../html/reciprocal_of_mcr.html)
* [top_hazard_quotient](../html/top_hazard_quotient.html)
* [classify_mixture](../html/classify_mixture.html)

Summarising indicators:

* [mcr_summary](../html/mcr_summary.html)
* [mcr_chart](../html/mcr_chart.html)
* [thq_pairs](../html/thq_pairs.html)
* [thq_by_group](../html/thq_by_group.html)

Application of the approach according to a classification

* [mcr_approach_by_class](../html/mcr_approach_by_class.html)
* [mcr_summary_by_class](../html/mcr_summary_by_class.html)
* [mcr_chart_by_class](../html/mcr_chart_by_class.html)
* [thq_pairs_by_class](../html/thq_pairs_by_class.html)
* [thq_by_group_by_class](../html/thq_by_group_by_class.html)



# About lists

Computations on lists:

* [intersect_on_list](../html/intersect_on_list.html)
* [union_on_list](../html/union_on_list.html)
* [table_on_list](../html/table_on_list.html)

Transformation of lists and transformation into lists:

* [invert_list](../html/invert_list.html)
* [coerce_list](../html/coerce_list.html)
* [coerce_to_list](../html/coerce_to_list.html)



---
